name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v26
    - uses: Swatinem/rust-cache@v2.7.0
      with:
        shared-key: nix-rust
    - name: Check formatting
      run: nix develop -c cargo fmt --all --check
    - name: Run Clippy
      run: nix develop -c cargo clippy --workspace --all-targets --all-features -- -D warnings
    - name: Build
      run: nix develop -c cargo build
    - name: Run tests
      run: nix develop -c cargo test --workspace

  miri:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
        - norn-channel
        - norn-multicore
        - norn-nursery
        - norn-task
        - norn-executor
        - norn-timer
        - norn-util

    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v26
    - uses: Swatinem/rust-cache@v2.7.0
      with:
        shared-key: nix-miri-${{ matrix.package }}
    - name: Run Miri (${{ matrix.package }})
      run: nix develop -c cargo miri test -p ${{ matrix.package }}
